# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  # about: /about
  # RSS: /atom.xml
  # essay: /categories/essay
  # frontend: /categories/frontend

# favicon
favicon: /favicon.ico


# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: balance

## Banderole
# Header Style
# line | block
header-style: block

# Article Header Sign
header_sign: ＄

# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: blue

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  # license: MIT

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    # wechat:
    # paypal:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: true

  # disqus:
  # livere_datauid:

  # changyan:
  #   appid: cyu3LUqFV
  #   appkey: 2fab6348aaa253b461e5d6e4c1b1b26b

  # gitment:
  #   owner: ddzy
  #   repo: ddzy.github.io
  #   client_id: 'da227abbfeb5b4d39457'
  #   client_secret: 'd861af429b9fd372e91933c6c20d2daeb872dc4e'

  gitalk:
    owner: ddzy
    repo: blog
    client_id: 45d303490a6b33b33a74
    client_secret: cf3b8d0a0721a1fec9c38847c76d998fd0f72d07
    admin: [ddzy]

# sub //Please just fill out ID.
sub:
  # facebook: 1
  # twitter: 2
  # instagram: 3
  # weibo: 4
  # zhihu: 5
  # github: 6
  # linkedin: 7
  # douban: 8
  zhihu: bu-jing-tong-jsbu-zhao-dui-xiang-81/activities
  github: ddzy

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google:
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: true

# ===========================================
# Theme Settings
# ===========================================

# mathjax
mathjax: true

# lightbox
lightbox: true

# lazyload
lazyload: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2018

# plugin
# plugins:

# about
# self:
self: FE

# ===========================================
# Search Settings
# ===========================================

# Search
search:
  enable: true
  label: 搜索一下？
  baseUrl: /blog

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 2.4

#theme_author: Co1MugX
